title: Parul Sharma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A nomad Data Scientist who loves training neurons of brain and machines.  
  <br><br>
  Other than research, NLP and Computer Vision you can find me cooking, decorating corners of my house or may be training my muscles.
  <br><br>
  <a href="https://www.linkedin.com/in/parul-s-216432178/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
